version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: indra-backend
    ports:
      - "8001:8001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/indra
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: indra-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
